// <auto-generated />
namespace QLDX_API_V1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mydb16 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mydb16));
        
        string IMigrationMetadata.Id
        {
            get { return "202006020519270_mydb16"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
