// <auto-generated />
namespace QLDX_API_V1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mydb11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mydb11));
        
        string IMigrationMetadata.Id
        {
            get { return "202005290636470_mydb11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
